version: '2'
services :
  web :
    build : .
    links :
      - db
    ports :
      - 80:80
      - 443:443
    volumes :
      - ./www:/var/www/html
  db :
    image : mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD : mdp
      MYSQL_USER : glpiuser
      MYSQL_PASSWORD : glpimdp
      MYSQL_DATABASE : glpidb
    ports :
      - 3306:3306
